### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Xassodosdedos** [heyleao/Fortinet-Backup#1]
When installing I get message about syntax error:

c:\scripts>c:\Python311\Scripts\pyinstaller.exe --onefile "Gerar arquivos Fortinet v2.6.py"
372 INFO: PyInstaller: 6.1.0
373 INFO: Python: 3.11.3
387 INFO: Platform: Windows-10-10.0.19045-SP0
388 INFO: wrote c:\scripts\Gerar arquivos Fortinet v2.6.spec
399 INFO: Extending PYTHONPATH with paths
['c:\\scripts']
736 INFO: checking Analysis
737 INFO: Building Analysis because Analysis-00.toc is non existent
739 INFO: Initializing module dependency graph...
741 INFO: Caching module graph hooks...
756 INFO: Analyzing base_library.zip ...
2197 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
2260 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
3599 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Python311\\Lib\\site-packages\\PyInstaller\\hooks'...
4664 INFO: Caching module dependency graph...
4755 INFO: Running Analysis Analysis-00.toc
4756 INFO: Looking for Python shared library...
4762 INFO: Using Python shared library: C:\Python311\python311.dll
4763 INFO: Analyzing c:\scripts\Gerar arquivos Fortinet v2.6.py

Syntax error in c:\scripts\Gerar arquivos Fortinet v2.6.py
  File "C:\scripts\Gerar arquivos Fortinet v2.6.py", line 7
     <!DOCTYPE html>
     ^
 SyntaxError: invalid syntax

I using python 3.11.3 over windows 10 22H2 x64

**Comment by heyleao** [comment]
Are you using the script or installer?
I tryed on my windows 11 22H2 and windows 10 22h2 no problem at all.

**Comment by Xassodosdedos** [comment]
I am running the steps like they are specified, c:\Python311\Scripts\pyinstaller.exe --onefile "Gerar arquivos Fortinet v2.6.py"

**Comment by heyleao** [comment]
Ok, you will need to install dependencies, later i'll update the readme file.

pip3 install os
pip3 install paramiko
pip3 install tkinter

If you dont wanna mess with codes, try to use the installer
https://github.com/heyleao/Fortinet-Backup/releases/tag/v2.6
